"""empty message

Revision ID: 9eea8ffb77c4
Revises: a0b963286809
Create Date: 2018-07-28 18:44:30.641058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eea8ffb77c4'
down_revision = 'a0b963286809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tm_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('invited_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_id'], ['tm_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_name'),
    sa.UniqueConstraint('token')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=32), nullable=True),
    sa.Column('username', sa.VARCHAR(length=32), nullable=True),
    sa.Column('token', sa.VARCHAR(length=32), nullable=True),
    sa.Column('invited_by_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_name'),
    sa.UniqueConstraint('token')
    )
    op.drop_table('tm_user')
    # ### end Alembic commands ###
